# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_giris(object):
    def setupUi(self, giris):
        giris.setObjectName("giris")
        giris.resize(404, 269)
        self.lineEdit = QtWidgets.QLineEdit(giris)
        self.lineEdit.setGeometry(QtCore.QRect(150, 90, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(giris)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 130, 141, 22))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(giris)
        self.label.setGeometry(QtCore.QRect(70, 90, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(giris)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 31, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(giris)
        self.pushButton.setGeometry(QtCore.QRect(110, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(giris)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 200, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(giris)
        self.checkBox.setGeometry(QtCore.QRect(170, 160, 111, 20))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(giris)
        QtCore.QMetaObject.connectSlotsByName(giris)

    def retranslateUi(self, giris):
        _translate = QtCore.QCoreApplication.translate
        giris.setWindowTitle(_translate("giris", "Giriş"))
        self.label.setText(_translate("giris", "Kullanıcı Adı:"))
        self.label_2.setText(_translate("giris", "Şifre:"))
        self.pushButton.setText(_translate("giris", "Giriş"))
        self.pushButton_2.setText(_translate("giris", "Kapat"))
        self.checkBox.setText(_translate("giris", "Şifreyi Göster"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    giris = QtWidgets.QWidget()
    ui = Ui_giris()
    ui.setupUi(giris)
    giris.show()
    sys.exit(app.exec_())
