# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plaka_tespit_resim.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resim_tespit(object):
    def setupUi(self, resim_tespit):
        resim_tespit.setObjectName("resim_tespit")
        resim_tespit.resize(522, 703)
        self.groupBox = QtWidgets.QGroupBox(resim_tespit)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 481, 201))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 271, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 30, 31, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.resim_goster = QtWidgets.QPushButton(self.groupBox)
        self.resim_goster.setGeometry(QtCore.QRect(330, 30, 93, 28))
        self.resim_goster.setObjectName("resim_goster")
        self.plaka_oku = QtWidgets.QPushButton(self.groupBox)
        self.plaka_oku.setGeometry(QtCore.QRect(330, 70, 93, 28))
        self.plaka_oku.setObjectName("plaka_oku")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_3.setObjectName("label_3")
        self.okunan_plaka = QtWidgets.QLabel(self.groupBox)
        self.okunan_plaka.setGeometry(QtCore.QRect(110, 90, 151, 16))
        self.okunan_plaka.setObjectName("okunan_plaka")
        self.giris_izni = QtWidgets.QLabel(self.groupBox)
        self.giris_izni.setGeometry(QtCore.QRect(110, 120, 131, 16))
        self.giris_izni.setObjectName("giris_izni")
        self.musteriadi = QtWidgets.QLabel(self.groupBox)
        self.musteriadi.setGeometry(QtCore.QRect(110, 150, 191, 16))
        self.musteriadi.setObjectName("musteriadi")
        self.label_resim = QtWidgets.QLabel(resim_tespit)
        self.label_resim.setGeometry(QtCore.QRect(30, 230, 421, 411))
        self.label_resim.setScaledContents(True)
        self.label_resim.setObjectName("label_resim")

        self.retranslateUi(resim_tespit)
        QtCore.QMetaObject.connectSlotsByName(resim_tespit)

    def retranslateUi(self, resim_tespit):
        _translate = QtCore.QCoreApplication.translate
        resim_tespit.setWindowTitle(_translate("resim_tespit", "Resim ile Plaka Tespiti"))
        self.groupBox.setTitle(_translate("resim_tespit", "Plaka Tespit"))
        self.pushButton_2.setText(_translate("resim_tespit", "..."))
        self.resim_goster.setText(_translate("resim_tespit", "Resmi Göster"))
        self.plaka_oku.setText(_translate("resim_tespit", "Plaka Oku"))
        self.label.setText(_translate("resim_tespit", "Okunan Plaka:"))
        self.label_2.setText(_translate("resim_tespit", "Giriş İzni:"))
        self.label_3.setText(_translate("resim_tespit", "Müşteri Adı:"))
        self.okunan_plaka.setText(_translate("resim_tespit", "-"))
        self.giris_izni.setText(_translate("resim_tespit", "-"))
        self.musteriadi.setText(_translate("resim_tespit", "-"))
        self.label_resim.setText(_translate("resim_tespit", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    resim_tespit = QtWidgets.QWidget()
    ui = Ui_resim_tespit()
    ui.setupUi(resim_tespit)
    resim_tespit.show()
    sys.exit(app.exec_())
